module 5 completed
js-tasks-ru/jsbasic-20221028_kirsharik pull request #3
Opened 2022-11-17 17:13 UTC by LateNever

2022-11-17 17:14 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-18 15:19 UTC, koalex requested changes
Исправить замечания (говорил об этом на занятии)

2022-11-18 15:19 UTC, koalex commented on 5-module/1-task/index.js
> +  function hide () {this.setAttribute('hidden', true)};
`this.hidden = true;`

2022-11-18 15:19 UTC, koalex commented on 5-module/2-task/index.js
> +     text.setAttribute('hidden', true)
text.hidden = true;

2022-11-18 15:19 UTC, koalex commented on 5-module/2-task/index.js
> +      text.removeAttribute('hidden')
`text.hidden = false;`

2022-11-21 15:23 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-22 06:27 UTC, koalex approved these changes

2022-11-22 06:27 UTC, koalex commented on 5-module/2-task/index.js
> +    if (text.hidden == false) {
Можно так: `text.hidden = !text.hidden;`

2022-11-22 06:27 UTC, merged